import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { Buffer } from "node:buffer";
import { encodeControl, encodeData, MuxDecoder, type ControlMessage } from "../src/remote/mux.js";
import type { SessionMeta } from "../src/types.js";

// Byte-exact cross-language pin: the committed fixtures (generated by
// scripts/gen-remote-fixtures.ts) must equal what the Bun encoder produces here,
// and the Rust integration test asserts its encoder produces the same bytes
// (rust/climon-remote/tests/fixtures.rs). This guarantees a Rust uplink can talk
// to a Bun ingest and vice-versa.

const fixtures = JSON.parse(
  readFileSync(join(import.meta.dir, "..", "fixtures", "remote", "mux-frames.json"), "utf8")
) as Record<string, string>;

// Field order matches the Rust SessionMeta struct so JSON.stringify == serde_json.
const meta = {
  id: "s1",
  command: ["bash", "-lc", "echo hi"],
  displayCommand: "bash -lc echo hi",
  cwd: "/home/dev",
  status: "running",
  priorityReason: "running",
  cols: 80,
  rows: 24,
  socketPath: "tcp://127.0.0.1:9000",
  createdAt: "2026-01-01T00:00:00.000Z",
  updatedAt: "2026-01-01T00:00:00.000Z",
  lastActivityAt: "2026-01-01T00:00:00.000Z"
} as unknown as SessionMeta;

const controls: Record<string, ControlMessage> = {
  hello: { kind: "hello", clientId: "devbox-abc" },
  "session-added": { kind: "session-added", meta },
  "session-updated": {
    kind: "session-updated",
    id: "s1",
    patch: { status: "completed", priorityReason: "completed" }
  },
  "session-removed": { kind: "session-removed", id: "a" },
  attach: { kind: "attach", id: "s1" },
  detach: { kind: "detach", id: "s1" },
  ping: { kind: "ping" },
  pong: { kind: "pong" }
};

describe("remote mux cross-language fixtures", () => {
  for (const [name, msg] of Object.entries(controls)) {
    test(`bun encodeControl matches fixture control:${name}`, () => {
      expect(Buffer.from(encodeControl(msg)).toString("hex")).toBe(fixtures[`control:${name}`]);
    });
  }

  test("bun encodeData matches fixture data:sess-1", () => {
    expect(Buffer.from(encodeData("sess-1", Buffer.from([1, 2, 3, 4]))).toString("hex")).toBe(
      fixtures["data:sess-1"]
    );
  });

  test("bun encodeData matches fixture data:empty", () => {
    expect(Buffer.from(encodeData("x", Buffer.from([]))).toString("hex")).toBe(fixtures["data:empty"]);
  });

  test("bun MuxDecoder round-trips the committed session-added frame", () => {
    const bytes = Buffer.from(fixtures["control:session-added"], "hex");
    const out = new MuxDecoder().push(bytes);
    expect(out).toEqual([{ type: "control", message: { kind: "session-added", meta } }]);
  });

  test("bun MuxDecoder decodes the committed data frame", () => {
    const bytes = Buffer.from(fixtures["data:sess-1"], "hex");
    const out = new MuxDecoder().push(bytes);
    expect(out.length).toBe(1);
    expect(out[0]).toMatchObject({ type: "data", sessionId: "sess-1" });
    expect((out[0] as { data: Buffer }).data).toEqual(Buffer.from([1, 2, 3, 4]));
  });
});
