#!/usr/bin/env bun
/**
 * Reads xterm.js, xterm.css, and addon-fit.js from node_modules and writes
 * src/server/embedded-assets.ts with the file contents as base64 Buffer constants.
 * This allows `bun build --compile` to produce a standalone binary with no
 * runtime dependency on node_modules.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";

const projectRoot = dirname(dirname(import.meta.path));

const assets = [
  { varName: "XTERM_JS", specifier: "@xterm/xterm/lib/xterm.js" },
  { varName: "XTERM_CSS", specifier: "@xterm/xterm/css/xterm.css" },
  { varName: "ADDON_FIT_JS", specifier: "@xterm/addon-fit/lib/addon-fit.js" },
];

const lines: string[] = [
  `// Auto-generated by scripts/embed-assets.ts — do not edit manually.`,
  `import { Buffer } from "node:buffer";`,
  ``,
];

for (const asset of assets) {
  const resolved = Bun.resolveSync(asset.specifier, projectRoot);
  const content = readFileSync(resolved);
  const b64 = content.toString("base64");
  lines.push(`export const ${asset.varName} = Buffer.from("${b64}", "base64");`);
}

lines.push(``);

const outPath = resolve(projectRoot, "src/server/embedded-assets.ts");
writeFileSync(outPath, lines.join("\n"));
console.log(`✓ Wrote ${outPath} (${assets.length} assets embedded)`);
